"""init

Revision ID: 7e2c23d80c6e
Revises: 
Create Date: 2026-05-22 15:23:06.457946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e2c23d80c6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_pages_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21360_books_pages_link_pidx'))

    op.drop_table('books_pages_link')
    op.drop_table('users')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21217_comments_idx'))
        batch_op.drop_index(batch_op.f('idx_21217_sqlite_autoindex_comments_1'))

    op.drop_table('comments')
    op.drop_table('remote_auth_token')
    with op.batch_alter_table('sso_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sso_users_email'))
        batch_op.drop_index(batch_op.f('ix_sso_users_google_id'))

    op.drop_table('sso_users')
    op.drop_table('kobo_reading_state')
    op.drop_table('user_session')
    op.drop_table('annotations_fts_docsize')
    with op.batch_alter_table('custom_columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21227_custom_columns_idx'))
        batch_op.drop_index(batch_op.f('idx_21227_sqlite_autoindex_custom_columns_1'))

    op.drop_table('custom_columns')
    op.drop_table('book_shelf_link')
    op.drop_table('kobo_statistics')
    with op.batch_alter_table('books_publishers_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21205_books_publishers_link_aidx'))
        batch_op.drop_index(batch_op.f('idx_21205_books_publishers_link_bidx'))
        batch_op.drop_index(batch_op.f('idx_21205_sqlite_autoindex_books_publishers_link_1'))

    op.drop_table('books_publishers_link')
    with op.batch_alter_table('library_id', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21258_sqlite_autoindex_library_id_1'))

    op.drop_table('library_id')
    with op.batch_alter_table('books_authors_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21193_books_authors_link_aidx'))
        batch_op.drop_index(batch_op.f('idx_21193_books_authors_link_bidx'))
        batch_op.drop_index(batch_op.f('idx_21193_sqlite_autoindex_books_authors_link_1'))

    op.drop_table('books_authors_link')
    op.drop_table('annotations_fts_stemmed_config')
    op.drop_table('annotations_fts_config')
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21241_sqlite_autoindex_feeds_1'))

    op.drop_table('feeds')
    op.drop_table('annotations_fts_stemmed_data')
    op.drop_table('archived_book')
    with op.batch_alter_table('metadata_dirtied', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21263_sqlite_autoindex_metadata_dirtied_1'))

    op.drop_table('metadata_dirtied')
    with op.batch_alter_table('books_languages_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21196_books_languages_link_aidx'))
        batch_op.drop_index(batch_op.f('idx_21196_books_languages_link_bidx'))
        batch_op.drop_index(batch_op.f('idx_21196_sqlite_autoindex_books_languages_link_1'))

    op.drop_table('books_languages_link')
    op.drop_table('oauth')
    op.drop_table('annotations_fts')
    with op.batch_alter_table('books_series_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21211_books_series_link_aidx'))
        batch_op.drop_index(batch_op.f('idx_21211_books_series_link_bidx'))
        batch_op.drop_index(batch_op.f('idx_21211_sqlite_autoindex_books_series_link_1'))

    op.drop_table('books_series_link')
    op.drop_table('annotations_fts_stemmed_idx')
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21236_data_idx'))
        batch_op.drop_index(batch_op.f('idx_21236_formats_idx'))
        batch_op.drop_index(batch_op.f('idx_21236_sqlite_autoindex_data_1'))

    op.drop_table('data')
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21172_sqlite_autoindex_authors_1'))

    op.drop_table('authors')
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21274_publishers_idx'))
        batch_op.drop_index(batch_op.f('idx_21274_sqlite_autoindex_publishers_1'))

    op.drop_table('publishers')
    op.drop_table('kobo_bookmark')
    op.drop_table('oauthProvider')
    with op.batch_alter_table('annotations_dirtied', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21266_sqlite_autoindex_annotations_dirtied_1'))

    op.drop_table('annotations_dirtied')
    with op.batch_alter_table('conversion_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21222_conversion_options_idx_a'))
        batch_op.drop_index(batch_op.f('idx_21222_conversion_options_idx_b'))
        batch_op.drop_index(batch_op.f('idx_21222_sqlite_autoindex_conversion_options_1'))

    op.drop_table('conversion_options')
    op.drop_table('shelf_archive')
    op.drop_table('flask_settings')
    op.drop_table('kobo_synced_books')
    op.drop_table('annotations_fts_data')
    op.drop_table('annotations_fts_stemmed_docsize')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21304_annot_idx'))
        batch_op.drop_index(batch_op.f('idx_21304_sqlite_autoindex_annotations_1'))

    op.drop_table('annotations')
    op.drop_table('shelf')
    with op.batch_alter_table('books_ratings_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21208_books_ratings_link_aidx'))
        batch_op.drop_index(batch_op.f('idx_21208_books_ratings_link_bidx'))
        batch_op.drop_index(batch_op.f('idx_21208_sqlite_autoindex_books_ratings_link_1'))

    op.drop_table('books_ratings_link')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21292_sqlite_autoindex_tags_1'))
        batch_op.drop_index(batch_op.f('idx_21292_tags_idx'))

    op.drop_table('tags')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21280_sqlite_autoindex_ratings_1'))

    op.drop_table('ratings')
    op.drop_table('annotations_fts_idx')
    with op.batch_alter_table('books_tags_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21214_books_tags_link_aidx'))
        batch_op.drop_index(batch_op.f('idx_21214_books_tags_link_bidx'))
        batch_op.drop_index(batch_op.f('idx_21214_sqlite_autoindex_books_tags_link_1'))

    op.drop_table('books_tags_link')
    with op.batch_alter_table('books_plugin_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21200_sqlite_autoindex_books_plugin_data_1'))

    op.drop_table('books_plugin_data')
    op.drop_table('settings')
    op.drop_table('bookmark')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21180_authors_idx'))
        batch_op.drop_index(batch_op.f('idx_21180_books_idx'))

    op.drop_table('books')
    op.drop_table('thumbnail')
    op.drop_table('aws_credentials')
    op.drop_table('downloads')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21252_languages_idx'))
        batch_op.drop_index(batch_op.f('idx_21252_sqlite_autoindex_languages_1'))

    op.drop_table('languages')
    with op.batch_alter_table('identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21246_sqlite_autoindex_identifiers_1'))

    op.drop_table('identifiers')
    op.drop_table('annotations_fts_stemmed')
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21269_sqlite_autoindex_preferences_1'))

    op.drop_table('preferences')
    op.drop_table('book_read_link')
    with op.batch_alter_table('last_read_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21298_lrp_idx'))
        batch_op.drop_index(batch_op.f('idx_21298_sqlite_autoindex_last_read_positions_1'))

    op.drop_table('last_read_positions')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_21286_series_idx'))
        batch_op.drop_index(batch_op.f('idx_21286_sqlite_autoindex_series_1'))

    op.drop_table('series')
    op.drop_table('registration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('allow', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('registration_pkey'))
    )
    op.create_table('series',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21286_series_pkey'))
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21286_sqlite_autoindex_series_1'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('idx_21286_series_idx'), ['name'], unique=False)

    op.create_table('last_read_positions',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('device', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cfi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('epoch', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('pos_frac', sa.REAL(), server_default=sa.text("'0'::real"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21298_last_read_positions_pkey'))
    )
    with op.batch_alter_table('last_read_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21298_sqlite_autoindex_last_read_positions_1'), ['user', 'device', 'book', 'format'], unique=True)
        batch_op.create_index(batch_op.f('idx_21298_lrp_idx'), ['book'], unique=False)

    op.create_table('book_read_link',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('read_status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_time_started_reading', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('times_started_reading', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('book_read_link_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('book_read_link_pkey'))
    )
    op.create_table('preferences',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('val', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21269_preferences_pkey'))
    )
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21269_sqlite_autoindex_preferences_1'), ['key'], unique=True)

    op.create_table('annotations_fts_stemmed',
    sa.Column('searchable_text', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('identifiers',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), server_default=sa.text("'isbn'::text"), autoincrement=False, nullable=True),
    sa.Column('val', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21246_identifiers_pkey'))
    )
    with op.batch_alter_table('identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21246_sqlite_autoindex_identifiers_1'), ['book', 'type'], unique=True)

    op.create_table('languages',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('lang_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21252_languages_pkey'))
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21252_sqlite_autoindex_languages_1'), ['lang_code'], unique=True)
        batch_op.create_index(batch_op.f('idx_21252_languages_idx'), ['lang_code'], unique=False)

    op.create_table('downloads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('downloads_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('downloads_pkey'))
    )
    op.create_table('aws_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aws_access_key_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('aws_secret_access_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('default_region', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('default_output_format', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('bucket_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('aws_credentials_pkey'))
    )
    op.create_table('thumbnail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('format', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('thumbnail_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('thumbnail_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('books',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), server_default=sa.text("'Unknown'::text"), autoincrement=False, nullable=True),
    sa.Column('sort', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('pubdate', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('series_index', sa.REAL(), server_default=sa.text("'1'::real"), autoincrement=False, nullable=True),
    sa.Column('author_sort', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('has_cover', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('last_modified', postgresql.TIMESTAMP(), server_default=sa.text("'2000-01-01 00:00:00'::timestamp without time zone"), autoincrement=False, nullable=True),
    sa.Column('isbn', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('flags', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21180_books_pkey'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21180_books_idx'), ['sort'], unique=False)
        batch_op.create_index(batch_op.f('idx_21180_authors_idx'), ['author_sort'], unique=False)

    op.create_table('bookmark',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('format', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bookmark_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookmark_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookmark_pkey'))
    )
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mail_server', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mail_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mail_use_ssl', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('mail_login', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mail_password_e', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mail_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mail_from', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mail_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mail_server_type', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('mail_gmail_token', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('config_calibre_dir', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_calibre_uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_calibre_split', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_calibre_split_dir', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_external_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_certfile', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_keyfile', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_trustedhosts', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_calibre_web_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_books_per_page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_random_books', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_authors_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_read_column', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_title_regex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_theme', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_log_level', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('config_logfile', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_access_log', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('config_access_logfile', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_uploading', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('config_anonbrowse', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('config_public_reg', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('config_remote_login', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_kobo_sync', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_default_role', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('config_default_show', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_default_language', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('config_default_locale', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('config_columns_to_ignore', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_denied_tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_allowed_tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_restricted_column', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('config_denied_column_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_allowed_column_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_use_goodreads', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_goodreads_api_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_register_email', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_login_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_kobo_proxy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_provider_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_port', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_authentication', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_serv_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_serv_password_e', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_serv_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_encryption', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_cacert_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_cert_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_key_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_dn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_user_object', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_member_user_object', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_openldap', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_group_object_filter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_group_members_field', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_ldap_group_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_kepubifypath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_converterpath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_binariesdir', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_calibre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_rarfile_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_upload_formats', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_unicode_filename', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_embed_metadata', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_updatechannel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_reverse_proxy_login_header_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_allow_reverse_proxy_header_login', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('schedule_start_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('schedule_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('schedule_generate_book_covers', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('schedule_generate_series_covers', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('schedule_reconnect', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('schedule_metadata_backup', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_password_policy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_password_min_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_password_number', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_password_lower', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_password_upper', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_password_character', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_password_special', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_session', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_ratelimiter', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_limiter_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_limiter_options', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_check_extensions', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_db_host', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_db_port', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_db_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_db_user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_db_password_e', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_db_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_database_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_use_postgresql', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_use_postgresql_metadata', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_postgresql_metadata_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('settings_pkey'))
    )
    op.create_table('books_plugin_data',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('val', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21200_books_plugin_data_pkey'))
    )
    with op.batch_alter_table('books_plugin_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21200_sqlite_autoindex_books_plugin_data_1'), ['book', 'name'], unique=True)

    op.create_table('books_tags_link',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('tag', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21214_books_tags_link_pkey'))
    )
    with op.batch_alter_table('books_tags_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21214_sqlite_autoindex_books_tags_link_1'), ['book', 'tag'], unique=True)
        batch_op.create_index(batch_op.f('idx_21214_books_tags_link_bidx'), ['book'], unique=False)
        batch_op.create_index(batch_op.f('idx_21214_books_tags_link_aidx'), ['tag'], unique=False)

    op.create_table('annotations_fts_idx',
    sa.Column('segid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('term', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pgno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term', name=op.f('idx_21320_sqlite_autoindex_annotations_fts_idx_1'))
    )
    op.create_table('ratings',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21280_ratings_pkey'))
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21280_sqlite_autoindex_ratings_1'), ['rating'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21292_tags_pkey'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21292_tags_idx'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_21292_sqlite_autoindex_tags_1'), ['name'], unique=True)

    op.create_table('books_ratings_link',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21208_books_ratings_link_pkey'))
    )
    with op.batch_alter_table('books_ratings_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21208_sqlite_autoindex_books_ratings_link_1'), ['book', 'rating'], unique=True)
        batch_op.create_index(batch_op.f('idx_21208_books_ratings_link_bidx'), ['book'], unique=False)
        batch_op.create_index(batch_op.f('idx_21208_books_ratings_link_aidx'), ['rating'], unique=False)

    op.create_table('shelf',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kobo_sync', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('shelf_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shelf_pkey'))
    )
    op.create_table('annotations',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('annot_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('annot_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('annot_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('searchable_text', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21304_annotations_pkey'))
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21304_sqlite_autoindex_annotations_1'), ['book', 'user_type', 'user', 'format', 'annot_type', 'annot_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_21304_annot_idx'), ['book'], unique=False)

    op.create_table('annotations_fts_stemmed_docsize',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sz', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21350_annotations_fts_stemmed_docsize_pkey'))
    )
    op.create_table('annotations_fts_data',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('block', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21315_annotations_fts_data_pkey'))
    )
    op.create_table('kobo_synced_books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('kobo_synced_books_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kobo_synced_books_pkey'))
    )
    op.create_table('flask_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flask_session_key', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('flask_settings_pkey'))
    )
    op.create_table('shelf_archive',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('shelf_archive_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shelf_archive_pkey'))
    )
    op.create_table('conversion_options',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21222_conversion_options_pkey'))
    )
    with op.batch_alter_table('conversion_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21222_sqlite_autoindex_conversion_options_1'), ['format', 'book'], unique=True)
        batch_op.create_index(batch_op.f('idx_21222_conversion_options_idx_b'), ['book'], unique=False)
        batch_op.create_index(batch_op.f('idx_21222_conversion_options_idx_a'), ['format'], unique=False)

    op.create_table('annotations_dirtied',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21266_annotations_dirtied_pkey'))
    )
    with op.batch_alter_table('annotations_dirtied', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21266_sqlite_autoindex_annotations_dirtied_1'), ['book'], unique=True)

    op.create_table('oauthProvider',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('oauth_client_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('oauth_client_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('oauthProvider_pkey'))
    )
    op.create_table('kobo_bookmark',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kobo_reading_state_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('progress_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('content_source_progress_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kobo_reading_state_id'], ['kobo_reading_state.id'], name=op.f('kobo_bookmark_kobo_reading_state_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kobo_bookmark_pkey'))
    )
    op.create_table('publishers',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21274_publishers_pkey'))
    )
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21274_sqlite_autoindex_publishers_1'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('idx_21274_publishers_idx'), ['name'], unique=False)

    op.create_table('authors',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21172_authors_pkey'))
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21172_sqlite_autoindex_authors_1'), ['name'], unique=True)

    op.create_table('data',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uncompressed_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21236_data_pkey'))
    )
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21236_sqlite_autoindex_data_1'), ['book', 'format'], unique=True)
        batch_op.create_index(batch_op.f('idx_21236_formats_idx'), ['format'], unique=False)
        batch_op.create_index(batch_op.f('idx_21236_data_idx'), ['book'], unique=False)

    op.create_table('annotations_fts_stemmed_idx',
    sa.Column('segid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('term', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pgno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term', name=op.f('idx_21345_sqlite_autoindex_annotations_fts_stemmed_idx_1'))
    )
    op.create_table('books_series_link',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('series', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21211_books_series_link_pkey'))
    )
    with op.batch_alter_table('books_series_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21211_sqlite_autoindex_books_series_link_1'), ['book'], unique=True)
        batch_op.create_index(batch_op.f('idx_21211_books_series_link_bidx'), ['book'], unique=False)
        batch_op.create_index(batch_op.f('idx_21211_books_series_link_aidx'), ['series'], unique=False)

    op.create_table('annotations_fts',
    sa.Column('searchable_text', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('oauth',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider_user_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('oauth_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_pkey'))
    )
    op.create_table('books_languages_link',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('lang_code', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('item_order', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21196_books_languages_link_pkey'))
    )
    with op.batch_alter_table('books_languages_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21196_sqlite_autoindex_books_languages_link_1'), ['book', 'lang_code'], unique=True)
        batch_op.create_index(batch_op.f('idx_21196_books_languages_link_bidx'), ['book'], unique=False)
        batch_op.create_index(batch_op.f('idx_21196_books_languages_link_aidx'), ['lang_code'], unique=False)

    op.create_table('metadata_dirtied',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21263_metadata_dirtied_pkey'))
    )
    with op.batch_alter_table('metadata_dirtied', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21263_sqlite_autoindex_metadata_dirtied_1'), ['book'], unique=True)

    op.create_table('archived_book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('archived_book_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('archived_book_pkey'))
    )
    op.create_table('annotations_fts_stemmed_data',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('block', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21340_annotations_fts_stemmed_data_pkey'))
    )
    op.create_table('feeds',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('script', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21241_feeds_pkey'))
    )
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21241_sqlite_autoindex_feeds_1'), ['title'], unique=True)

    op.create_table('annotations_fts_config',
    sa.Column('k', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('v', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('k', name=op.f('idx_21330_sqlite_autoindex_annotations_fts_config_1'))
    )
    op.create_table('annotations_fts_stemmed_config',
    sa.Column('k', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('v', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('k', name=op.f('idx_21355_sqlite_autoindex_annotations_fts_stemmed_config_1'))
    )
    op.create_table('books_authors_link',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('author', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21193_books_authors_link_pkey'))
    )
    with op.batch_alter_table('books_authors_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21193_sqlite_autoindex_books_authors_link_1'), ['book', 'author'], unique=True)
        batch_op.create_index(batch_op.f('idx_21193_books_authors_link_bidx'), ['book'], unique=False)
        batch_op.create_index(batch_op.f('idx_21193_books_authors_link_aidx'), ['author'], unique=False)

    op.create_table('library_id',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21258_library_id_pkey'))
    )
    with op.batch_alter_table('library_id', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21258_sqlite_autoindex_library_id_1'), ['uuid'], unique=True)

    op.create_table('books_publishers_link',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('publisher', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21205_books_publishers_link_pkey'))
    )
    with op.batch_alter_table('books_publishers_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21205_sqlite_autoindex_books_publishers_link_1'), ['book'], unique=True)
        batch_op.create_index(batch_op.f('idx_21205_books_publishers_link_bidx'), ['book'], unique=False)
        batch_op.create_index(batch_op.f('idx_21205_books_publishers_link_aidx'), ['publisher'], unique=False)

    op.create_table('kobo_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kobo_reading_state_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remaining_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spent_reading_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kobo_reading_state_id'], ['kobo_reading_state.id'], name=op.f('kobo_statistics_kobo_reading_state_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kobo_statistics_pkey'))
    )
    op.create_table('book_shelf_link',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shelf', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shelf'], ['shelf.id'], name=op.f('book_shelf_link_shelf_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('book_shelf_link_pkey'))
    )
    op.create_table('custom_columns',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datatype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mark_for_delete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('editable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('display', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=True),
    sa.Column('is_multiple', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('normalized', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21227_custom_columns_pkey'))
    )
    with op.batch_alter_table('custom_columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21227_sqlite_autoindex_custom_columns_1'), ['label'], unique=True)
        batch_op.create_index(batch_op.f('idx_21227_custom_columns_idx'), ['label'], unique=False)

    op.create_table('annotations_fts_docsize',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sz', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21325_annotations_fts_docsize_pkey'))
    )
    op.create_table('user_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('random', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expiry', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_session_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_session_pkey'))
    )
    op.create_table('kobo_reading_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('priority_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('kobo_reading_state_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kobo_reading_state_pkey'))
    )
    op.create_table('sso_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('picture', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sso_users_pkey'))
    )
    with op.batch_alter_table('sso_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sso_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sso_users_email'), ['email'], unique=True)

    op.create_table('remote_auth_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('auth_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('remote_auth_token_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('remote_auth_token_pkey')),
    sa.UniqueConstraint('auth_token', name=op.f('remote_auth_token_auth_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('comments',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_21217_comments_pkey'))
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21217_sqlite_autoindex_comments_1'), ['book'], unique=True)
        batch_op.create_index(batch_op.f('idx_21217_comments_idx'), ['book'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('role', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kindle_mail', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('locale', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('sidebar_view', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('default_language', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('denied_tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('allowed_tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('denied_column_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('allowed_column_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('view_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('kobo_only_shelves_sync', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('forum_avatar', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('forum_email_verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('users_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('books_pages_link',
    sa.Column('book', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('pages', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True),
    sa.Column('algorithm', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True),
    sa.Column('format', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('format_size', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('needs_scan', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book'], ['books.id'], name=op.f('books_pages_link_book_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book', name=op.f('idx_21360_books_pages_link_pkey'))
    )
    with op.batch_alter_table('books_pages_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_21360_books_pages_link_pidx'), ['needs_scan'], unique=False)

    # ### end Alembic commands ###
