"""add metadata.db to ORM

Revision ID: a5e4ee50f266
Revises: 0cbf2c05458b
Create Date: 2026-05-22 13:20:02.013165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e4ee50f266'
down_revision = '0cbf2c05458b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.alter_column('comments_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.drop_constraint(batch_op.f('forum_threads_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'forum_categories', ['category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('forum_threads_category_id_fkey'), 'forum_categories', ['category_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('comments_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
